/* DO NOT EDIT THIS FILE. IT IS GENERATED BY 'make setver'*/

package main

const (
	Version = "0.1.0-dev.1"
)

// Gitref variable is automatically set to the output of git-describe
// during the build process
var Gitref string
