issues:
  exclude-rules:
    - linters: staticcheck
      text: "S1002: should omit comparison to bool constant"
  exclude-use-default: true
  max-same-issues: 0
  max-issues-per-linter: 0

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - goimports
    - golint
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - unconvert
    - varcheck

output:
  uniq-by-line: false

run:
  timeout: 5m