issues:
  exclude-rules:
    - linters:
      - gosimple
      text: "S1002: should omit comparison to bool constant"
  exclude-use-default: true
  max-same-issues: 0
  max-issues-per-linter: 0

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - gci
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    # Re-add the `unused` linter when this issue is fixed and released in the golangci-lint
    # https://github.com/dominikh/go-tools/issues/1361
    # - unused

linters-settings:
  depguard:
    list-type: denylist
    include-go-root: true # check against stdlib
    packages-with-error-message:
      - io/ioutil: 'use "io" or "os" packages instead'
      - github.com/golang/protobuf: 'use "google.golang.org/protobuf"'
      - github.com/hashicorp/go-uuid: 'use "github.com/google/uuid" instead'
      - github.com/pborman/uuid: 'use "github.com/google/uuid" instead'
      - github.com/siddontang/go-log/log: 'use "github.com/sirupsen/logrus" instead'
      - github.com/siddontang/go/log: 'use "github.com/sirupsen/logrus" instead'
      - go.uber.org/atomic: 'use "sync/atomic" instead'
  misspell:
    locale: US
  gci:
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - prefix(github.com/gravitational/teleport-plugins) # Custom section: groups all imports with the specified Prefix.
    skip-generated: true # Skip generated files.
    custom-order: true # Required for "sections" to take effect.
  nolintlint:
    allow-unused: true # Enabled because of conditional builds / build tags.
    require-explanation: true
    require-specific: true
output:
  uniq-by-line: false

run:
  go: '1.19'
  skip-dirs:
    - (^|/)node_modules/
    - ^api/gen/
    - ^docs/
    - ^gen/
    - ^rfd/
    - ^web/
  skip-dirs-use-default: false
  timeout: 5m