issues:
  exclude-rules:
    - linters: gosimple
      text: "S1002: should omit comparison to bool constant"
  exclude-use-default: true
  max-same-issues: 0
  max-issues-per-linter: 0

linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - goimports
    - revive
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unused
    - unconvert

output:
  uniq-by-line: false

run:
  skip-dirs:
    - pkg/mod
  skip-dirs-use-default: false
  timeout: 5m
