FROM golang:1.16.0 AS build
RUN mkdir -p /go/src/github.com/gravitational/teleport-plugins/
WORKDIR /go/src/github.com/gravitational/teleport-plugins/
COPY . .
RUN cd access/slack
RUN make && ls access/slack/*

FROM ubuntu:18.04 as plugin
RUN mkdir -p tmp/slack
WORKDIR /tmp/slack
COPY --from=build /go/src/github.com/gravitational/teleport-plugins/access/slack/ .
RUN cp ./build/teleport-slack .
RUN ./install