apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "discord.fullname" . }}
  labels:
    {{- include "discord.labels" . | nindent 4 }}
data:
  teleport-discord.toml: |
    [teleport]
    addr = "{{ .Values.teleport.address }}"
    identity = "/var/lib/teleport/plugins/discord/auth_id"

    [discord]
    token = "/var/lib/teleport/plugins/discord/discord-token"

    [role_to_recipients]
    {{- range $role, $recipients := .Values.roleToRecipients }}
    {{ $role | toJson }} = {{ $recipients | toJson }}
    {{- end }}

    [log]
    output = "{{ .Values.log.output }}"
    severity = "{{ .Values.log.severity }}"
