// Code generated by _gen/main.go DO NOT EDIT
/*
Copyright 2015-2022 Gravitational, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"

	tfschema "github.com/gravitational/teleport-plugins/terraform/tfschema"
	apitypes "github.com/gravitational/teleport/api/types"
	"github.com/gravitational/trace"
)

// dataSourceTeleportNetworkRestrictionsType is the data source metadata type
type dataSourceTeleportNetworkRestrictionsType struct{}

// dataSourceTeleportNetworkRestrictions is the resource
type dataSourceTeleportNetworkRestrictions struct {
	p Provider
}

// GetSchema returns the data source schema
func (r dataSourceTeleportNetworkRestrictionsType) GetSchema(ctx context.Context) (tfsdk.Schema, diag.Diagnostics) {
	return tfschema.GenSchemaNetworkRestrictionsV4(ctx)
}

// NewDataSource creates the empty data source
func (r dataSourceTeleportNetworkRestrictionsType) NewDataSource(_ context.Context, p tfsdk.Provider) (tfsdk.DataSource, diag.Diagnostics) {
	return dataSourceTeleportNetworkRestrictions{
		p: *(p.(*Provider)),
	}, nil
}

// Read reads teleport NetworkRestrictions
func (r dataSourceTeleportNetworkRestrictions) Read(ctx context.Context, req tfsdk.ReadDataSourceRequest, resp *tfsdk.ReadDataSourceResponse) {
	networkRestrictionsI, err := r.p.Client.GetNetworkRestrictions(ctx)
	if err != nil {
		resp.Diagnostics.Append(diagFromWrappedErr("Error reading NetworkRestrictions", trace.Wrap(err), "network_restrictions"))
		return
	}

    var state types.Object
	networkRestrictions := networkRestrictionsI.(*apitypes.NetworkRestrictionsV4)
	diags := tfschema.CopyNetworkRestrictionsV4ToTerraform(ctx, networkRestrictions, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
}
