kind: Service
apiVersion: v1
metadata:
  name: {{ include "jira.fullname" . }}
  {{- if (or (eq .Values.chartMode "aws") .Values.serviceAnnotations) }}
  annotations:
    {{- if eq .Values.chartMode "aws" }}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    {{- end }}
    {{- if .Values.serviceAnnotations }}
      {{- toYaml .Values.serviceAnnotations | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  selector:
    {{- include "jira.selectorLabels" . | nindent 4 }}
  type: {{ .Values.serviceType }}
  ports:
  - name: https
    port: 443
    targetPort: 8443
