apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mattermost.fullname" . }}
  labels:
    {{- include "mattermost.labels" . | nindent 4 }}
data:
  teleport-mattermost.toml: |
    [teleport]
    addr = "{{ .Values.teleport.address }}"
    identity = "/var/lib/teleport/plugins/mattermost/auth_id"

    [mattermost]
    url        = "{{ .Values.mattermost.url }}"
    token      = "{{ .Values.mattermost.token }}"
    recipients = {{ .Values.mattermost.recipients | toJson }}

    [log]
    output = "{{ .Values.log.output }}"
    severity = "{{ .Values.log.severity }}"
