steps:
  - name: golang:1.17.10
    env:
      - TELEPORT_GET_VERSION=v9.0.4
    secretEnv:
      - TELEPORT_ENTERPRISE_LICENSE
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add - &&
        apt update && apt install -y software-properties-common &&
        apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main" &&
        apt update && apt install -y terraform &&
        make test

availableSecrets:
  secretManager:
  - versionName: projects/771512790633/secrets/ci-enterprise-license/versions/1
    env: TELEPORT_ENTERPRISE_LICENSE
options:
  machineType: E2_HIGHCPU_8
