#!/bin/sh

# github.com/gravitational/teleport contains private git submodules that can't be
# checkouted by dep, so we have to use git wrapper that ignores submodules

if [ -z $_GIT_ORIGIN ]; then
  echo "Don't use this wrapper directly";
  exit 1;
fi

if [ $1 == "submodule" ]; then
  echo "Ignoring submodules";
  exit 0;
fi

$_GIT_ORIGIN $@
