kind: role
metadata:
  name: terraform
spec:
  allow:
    rules:
      - resources:
        - user
        - role
        - token
        - trusted_cluster
        - github
        - oidc
        - saml
        - cluster_auth_preference
        - cluster_networking_config
        - session_recording_config
        - app
        - db
        verbs: ['list','create','read','update','delete']
version: v4
---
kind: user
metadata:
  name: terraform
spec:
  roles: ['terraform']
version: v2
