# fluentd forwarder example key file
storage-dir = "example/storage"
timeout = "10s"
batch = 10
namespace = "default"

[fluentd]
cert = "example/keys/client.crt"
key = "example/keys/client.key" 
ca = "example/keys/ca.crt"
url = "https://localhost:8888/test.log"

[teleport]
addr = "localhost:3025"
ca = "example/keys/tf.cas" 
cert = "example/keys/tf.crt"
key  = "example/keys/tf.key"
