name: Build MacOS (Darwin)

on:
  push:
    branches:
      - 'walt/*'
#   workflow_call:
#       arch:
#         description: 'Build architecture. Either amd64 or arm64'
#         required: true
#         type: string

jobs:
  build-release-artifacts:
    runs-on: macos-13-xl-arm64
    permissions:
      contents: read
    env:
      GO_VERSION: 1.21.1
      TELEPORT_VERSION: 14.0.0
      TERRAFORM_VERISON: 1.5.6
      GOMODCACHE: /tmp/gomodcache
      GOCACHE: /tmp/gocache
      # ARCH: ${{ inputs.arch }}
      ARCH: amd64
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: install terraform
        uses: hashicorp/setup-terraform@v2
        with:
           terraform_version: ${{ env.TERAFORM_VERSION }}
      - name: install teleport
        run: |
          mkdir -p teleport
          cd teleport
          curl --no-progress-meter -O https://cdn.teleport.dev/teleport-ent-v$TELEPORT_VERSION-darwin-amd64-bin.tar.gz
          tar -xzf teleport-ent-v$TELEPORT_VERSION-darwin-amd64-bin.tar.gz
          sudo ./teleport-ent/install
          teleport version
          cd -
          rm -rf teleport teleport-ent-v$TELEPORT_VERSION-darwin-amd64-bin.tar.gz
      - name: run tests
        env:
          TELEPORT_ENTERPRISE_LICENSE: ${{ secrets.TELEPORT_ENTERPRISE_LICENSE }}
        run: make test
