name: run-tests

on:
  push:
    branches: [ 'master', 'release/.*' ]
  pull_request:
    branches: [ 'master', 'release/.*' ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13.2
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.2
      id: go
      
    - name: Check out code into GOPATH
      uses: actions/checkout@v2

    - name: Get dependencies and run tests
      run: |
        export GOPATH=$RUNNER_WORKSPACE/go
        mkdir -p $GOPATH/bin $GOPATH/src/github.com/gravitational
        cp -ax $RUNNER_WORKSPACE/teleport-plugins $GOPATH/src/github.com/gravitational/
        git clone https://github.com/gravitational/teleport.git $GOPATH/src/github.com/gravitational/teleport
        cd $GOPATH/src/github.com/gravitational/teleport-plugins
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            $GOPATH/bin/dep ensure
        fi
        
    - name: Run Jira tests
      run: |
        export GOPATH=$RUNNER_WORKSPACE/go
        cd $RUNNER_WORKSPACE/go/src/github.com/gravitational/teleport-plugins
        make -C access/jirabot test
        
    - name: Run Slack tests
      run: |
        export GOPATH=$RUNNER_WORKSPACE/go
        cd $RUNNER_WORKSPACE/go/src/github.com/gravitational/teleport-plugins
        make -C access/slackbot test
        
    - name: Run Mattermost tests
      run: |
        export GOPATH=$RUNNER_WORKSPACE/go
        cd $RUNNER_WORKSPACE/go/src/github.com/gravitational/teleport-plugins
        make -C access/mattermost test
        
    - name: Run Pagerduty tests
      run: |
        export GOPATH=$RUNNER_WORKSPACE/go
        cd $RUNNER_WORKSPACE/go/src/github.com/gravitational/teleport-plugins
        make -C access/pagerduty test
